#!/bin/bash

#I have discovered a much easier way to install Verilator on linux_x64 systems since initially attempting this project.
#Verilator is packaged with oss-cad-suite which makes it as simple as downloading the release from github and updating PATH
#Instructions here: https://github.com/YosysHQ/oss-cad-suite-build?tab=readme-ov-file
#Credit: youtube video by XXXXX will update when off the plane

wget https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2024-12-17/oss-cad-suite-linux-x64-20241217.tgz
mkdir ~/tools
tar -xvf oss-cad-suite-linux-x64-20241217.tgz
mv oss-cad-suite ~/tools/
source ~/tools/oss-cad-suite/environment
