#!/bin/bash

echo "Installing dependencies: verilator, python-dev, gtkwave"
sudo apt install verilator python3-dev gtkwave

echo "Creating a python virtual environment"
rm -rf verif_venv
python3 -m venv verif_venv

echo "Installing cocotb"
source verif_venv/bin/activate
pip install --upgrade pip
pip install wheel cocotb
pip install ./simon_test
