#!/bin/bash

echo "Installing dependencies: make, python3, python3-pip, python3-venv"
sudo apt install make python3 python3-pip python3-venv

cd ..

echo "Creating a python virtual environment"
rm -rf verif_venv
python3 -m venv verif_venv

echo "Installing cocotb"
source verif_venv/bin/activate

pip install --upgrade pip
pip install wheel cocotb
pip install ./simon_test
